import type { ScanResult } from '../core/repoScanner.js';
import type { FrameworkInfo } from '../core/frameworkDetector.js';
import type { ArchitectureResult } from '../core/architectureAnalyzer.js';
import type { FileCategory } from '../core/fileClassifier.js';

/**
 * Generate AGENTS.md content from scanned project data.
 */
export function generateAgentsContent(
  scan: ScanResult,
  fw: FrameworkInfo,
  arch: ArchitectureResult,
  byCategory: Record<FileCategory, string[]>,
): string {
  const sections: string[] = [];

  sections.push('# AGENTS.md');
  sections.push('');
  sections.push('> Instructions for AI coding agents working on this project.');
  sections.push('> Generated by RepoLens AI.');
  sections.push('');

  // Project Overview
  sections.push('## Project Overview');
  sections.push('');
  sections.push(`- **Framework:** ${fw.framework} ${fw.version || ''}`);
  sections.push(`- **Language:** ${fw.language}`);
  sections.push(`- **Package Manager:** ${fw.packageManager}`);
  sections.push(`- **Architecture:** ${arch.style}`);
  sections.push(`- **Total Files:** ${scan.totalFiles}`);
  sections.push('');

  // Tech Stack
  sections.push('## Tech Stack');
  sections.push('');
  sections.push(`- Primary: ${fw.framework} (${fw.language})`);
  if (fw.additionalFrameworks.length > 0) {
    for (const lib of fw.additionalFrameworks) {
      sections.push(`- ${lib}`);
    }
  }
  sections.push('');

  // Folder Structure
  sections.push('## Folder Structure');
  sections.push('');
  sections.push('```');
  for (const dir of scan.directories.slice(0, 20)) {
    sections.push(dir + '/');
  }
  sections.push('```');
  sections.push('');

  // Important Files
  sections.push('## Important Files');
  sections.push('');
  for (const f of scan.importantFiles) {
    sections.push(`- \`${f}\``);
  }
  sections.push('');

  // Coding Rules
  sections.push('## Coding Rules');
  sections.push('');
  sections.push('1. **Analyze before editing** — Understand the existing architecture before making changes.');
  sections.push('2. **Minimal safe changes** — Make the smallest change that solves the problem.');
  sections.push('3. **Preserve architecture** — Follow the existing patterns and conventions.');
  sections.push('4. **No unnecessary rewrites** — Do not rewrite files that work correctly.');
  sections.push(`5. **Follow ${fw.language} conventions** — Use idiomatic ${fw.language} code.`);
  sections.push('6. **Keep files focused** — Each file should have a single responsibility.');
  sections.push('');

  // Security Rules
  sections.push('## Security Rules');
  sections.push('');
  sections.push('1. **Never commit secrets** — No API keys, tokens, or passwords in source code.');
  sections.push('2. **Protect .env files** — Never read or expose .env file contents.');
  sections.push('3. **Validate all input** — Never trust user input.');
  sections.push('4. **Use parameterized queries** — Never use raw SQL string concatenation.');
  sections.push('5. **No eval()** — Never use eval, exec, or similar dynamic code execution.');
  sections.push('6. **Preserve auth middleware** — Never remove authentication or authorization checks.');
  sections.push('');

  // Testing
  sections.push('## Testing');
  sections.push('');
  if (scan.hasTests) {
    sections.push('This project has tests. Always:');
    sections.push('- Run existing tests before and after changes');
    sections.push('- Add tests for new functionality');
    sections.push('- Never delete existing tests without explanation');
  } else {
    sections.push('This project currently lacks tests. When possible:');
    sections.push('- Add tests for critical business logic');
    sections.push('- Add tests for security-sensitive code');
  }
  sections.push('');

  // Workflow
  sections.push('## Workflow Rules');
  sections.push('');
  sections.push('1. Read relevant files before editing');
  sections.push('2. Check for existing patterns before creating new ones');
  sections.push('3. Summarize all changes made');
  sections.push('4. Flag any potential breaking changes');
  sections.push('5. Do not modify configuration files without explicit instruction');
  sections.push('');

  // Definition of Done
  sections.push('## Definition of Done');
  sections.push('');
  sections.push('A change is complete when:');
  sections.push('- [ ] Code compiles without errors');
  sections.push('- [ ] Existing tests pass');
  sections.push('- [ ] New tests added for new functionality');
  sections.push('- [ ] No secrets in source code');
  sections.push('- [ ] Changes are minimal and focused');
  sections.push('- [ ] Architecture patterns are preserved');
  sections.push('- [ ] Changes are summarized clearly');
  sections.push('');

  return sections.join('\n');
}
