import * as fs from 'node:fs';
import * as path from 'node:path';
import type { ScanResult } from '../core/repoScanner.js';
import type { FrameworkInfo } from '../core/frameworkDetector.js';
import type { ArchitectureResult } from '../core/architectureAnalyzer.js';
import type { RiskReport } from '../core/riskDetector.js';
import type { GitDiffResult } from '../core/gitDiff.js';
import type { FileCategory } from '../core/fileClassifier.js';

/**
 * Generate a markdown report file.
 */
export function generateMarkdownReport(options: {
  scan: ScanResult;
  framework: FrameworkInfo;
  architecture: ArchitectureResult;
  risks: RiskReport;
  byCategory: Record<FileCategory, string[]>;
  diff?: GitDiffResult;
  aiText?: string | null;
  outputPath?: string;
}): string {
  const { scan, framework, architecture, risks, byCategory, diff, aiText } = options;
  const lines: string[] = [];

  lines.push('# 🔍 RepoLens AI Report');
  lines.push('');
  lines.push(`> Generated on ${new Date().toISOString()}`);
  lines.push('');

  // Summary
  lines.push('## ✨ Project Summary');
  lines.push('');
  lines.push(`| Property | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Framework | ${framework.framework} ${framework.version || ''} |`);
  lines.push(`| Language | ${framework.language} |`);
  lines.push(`| Package Manager | ${framework.packageManager} |`);
  lines.push(`| Total Files | ${scan.totalFiles} |`);
  lines.push(`| Est. Lines of Code | ${scan.estimatedLinesOfCode.toLocaleString()} |`);
  lines.push(`| Languages | ${scan.languages.join(', ')} |`);
  if (framework.additionalFrameworks.length > 0) {
    lines.push(`| Libraries | ${framework.additionalFrameworks.join(', ')} |`);
  }
  lines.push('');

  // Architecture
  lines.push('## 🧠 Architecture');
  lines.push('');
  lines.push(`**Style:** ${architecture.style}`);
  lines.push('');
  if (architecture.layers.length > 0) {
    lines.push('### Layers');
    for (const l of architecture.layers) {
      lines.push(`- **${l.name}** (${l.files} files): ${l.examples.slice(0, 3).join(', ')}`);
    }
    lines.push('');
  }
  if (architecture.dataFlow.length > 0) {
    lines.push(`**Data Flow:** ${architecture.dataFlow.join(' → ')}`);
    lines.push('');
  }

  // Risks
  lines.push('## ⚠️ Risk Analysis');
  lines.push('');
  lines.push(`🔴 ${risks.summary.high} high | 🟡 ${risks.summary.medium} medium | 🟢 ${risks.summary.low} low`);
  lines.push('');
  if (risks.risks.length > 0) {
    lines.push('| Level | Category | Issue | File |');
    lines.push('|---|---|---|---|');
    for (const r of risks.risks) {
      const icon = r.level === 'high' ? '🔴' : r.level === 'medium' ? '🟡' : '🟢';
      lines.push(`| ${icon} ${r.level} | ${r.category} | ${r.message} | ${r.file || '-'} |`);
    }
    lines.push('');
  }

  // Modules
  lines.push('## 📦 Main Modules');
  lines.push('');
  const cats: [string, FileCategory][] = [
    ['Controllers', 'controller'], ['Services', 'service'], ['Models', 'model'],
    ['Routes', 'route'], ['Components', 'component'], ['Tests', 'test'],
  ];
  for (const [label, cat] of cats) {
    const files = byCategory[cat];
    if (files.length > 0) {
      lines.push(`### ${label} (${files.length})`);
      for (const f of files.slice(0, 10)) lines.push(`- ${f}`);
      lines.push('');
    }
  }

  // Suggestions
  if (architecture.suggestions.length > 0) {
    lines.push('## 🚀 Recommended Next Steps');
    lines.push('');
    for (const s of architecture.suggestions) lines.push(`- [ ] ${s}`);
    lines.push('');
  }

  // AI
  if (aiText) {
    lines.push('## 🤖 AI Analysis');
    lines.push('');
    lines.push(aiText);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [RepoLens AI](https://github.com/Harry-Kien/repolens-ai)*');

  const content = lines.join('\n');

  // Write to file if path specified
  const outputPath = options.outputPath || path.join(process.cwd(), 'repolens-report.md');
  fs.writeFileSync(outputPath, content, 'utf-8');

  return outputPath;
}
